#!/bin/bash

DB_LB_KEEPALIVED_VIP=172.30.0.200
DB_LB_PORT=3306
DATABASE_SCHEME=djangovuetemplate
PXC_USERNAME=root
PXC_PASSWORD=b0a1d2p3a4s5s6w7d
DATABASE_URL=mysql://${PXC_USERNAME}:${PXC_PASSWORD}@${DB_LB_KEEPALIVED_VIP}:${DB_LB_PORT}/${DATABASE_SCHEME}
DJANGO_SETTINGS_MODULE=backend.settings.prod
DJANGO_PORT=8080
WORKDIR=/root/django-vue-template


/usr/local/bin/gunicorn --env DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE} --env DATABASE_URL=${DATABASE_URL} -b :${DJANGO_PORT} --chdir ${WORKDIR} backend.wsgi
